sh  pyrs/core/mantid_fit_peak.py
sh  pyrs/core/mantid_helper.py
sh  pyrs/core/peak_fit_engine.py
sh  pyrs/core/peak_fit_factory.py
sh  pyrs/core/pyrscore.py
sh  pyrs/core/reduction_manager.py
sh  pyrs/core/workspaces.py
sh  pyrs/utilities/rs_project_file.py
sh  scripts/convert_hzb_data.py
sh  scripts/preparetest/convert_hzb_data.py
sh  scripts/preparetest/convert_xray_data.py
sh  tests/quicktest/plot_reduced_data.py
sh  tests/unittest/fit_peaks_test.py
