#!/usr/bin/python
import sys
import imp
# try:
from qtpy import QtCore
from qtpy.QtWidgets import QDialog, QApplication
# from pyrs.utilities import load_ui
# from PyQt4 import QtCore as QtCore
# from PyQt4.QtGui import QDialog, QApplication
# from PyQt4.uic import loadUi as load_ui
# except ImportError:
#     imp.find_module('IPython.paths')  # This is for WZ's develop
#     imp.find_module('qtconsole')  # This is for Analysis cluster
#     from PyQt5 import QtCore as QtCore
#     from PyQt5.QtWidgets import QDialog, QApplication
#     from PyQt5.uic import loadUi as load_ui
import pyrs.interface.pyrs_main


def main(argv):
    """
    """
    if QApplication.instance():
        _app = QApplication.instance()
    else:
        _app = QApplication(sys.argv)
    return _app


if __name__ == '__main__':
    # Main application
    app = main(sys.argv)

    main_window = pyrs.interface.pyrs_main.PyRSLauncher()  # .FourCircleMainWindow()
    main_window.show()

    app.exec_()
