# load information from setup.cfg/setup.py
{% set data = load_setup_py_data() %}
{% set license = data.get('license') %}
{% set description = data.get('description') %}
{% set url = data.get('url') %}
# this will reproduce the version from tags to match versioningit
{% set version_tag = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
{% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}
{% set version_number = '_' + version_number if version_number != '0' else '' %}

{% set version = version_tag + version_number %}

package:
  name: "pyrs"
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  string: py{{py}}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - versioningit

  build:
    - configparser
    - mantidworkbench=6.4.0
    - qtpy
    - pytest
    - uncertainties
    - vtk
    - setuptools
    - versioningit

  run:
    - configparser
    - mantidworkbench=6.4.0
    - qtpy
    - uncertainties
    - vtk

test:
  imports:
    - pyrs

about:
  home: {{ url }}
  license: {{ license }}
  license_family: GPL3
  license_file: ../LICENSE
  summary: {{ description }}

extra:
  recipe-maintainers:
    - JeanBilheux
    - peterfpeterson
    - fanchercm
