# load information from setup.cfg/setup.py
{% set pyproject = load_file_data('pyproject.toml') %}
{% set project = pyproject.get('project', {}) %}
{% set license = project.get('license').get('text') %}
{% set description = project.get('description') %}
{% set project_url = pyproject.get('project', {}).get('urls') %}
{% set url = project_url.get('homepage') %}
# this will reproduce the version from tags to match versioningit
# this will get the version set by environment variable
{% set version = environ.get('VERSION') %}
{% set version_number = version.split('+')[0] %}
# change the build number by hand if you want to rebuild the package
{% set build_number = 0 %}

package:
  name: "pyrs"
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  string: py{{py}}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - versioningit

  build:
    - configparser
    - mantidworkbench
    - qtpy
    - pytest
    - uncertainties
    - setuptools
    - versioningit
    - pandas

  run:
    - configparser
    - mantidworkbench
    - qtpy
    - uncertainties
    - pandas

test:
  imports:
    - pyrs

about:
  home: {{ url }}
  license: {{ license }}
  license_family: GPL3
  license_file: ../LICENSE
  summary: {{ description }}

extra:
  recipe-maintainers:
    - JeanBilheux
    - peterfpeterson
    - fanchercm
