import os

version_tag = os.environ.get('GIT_DESCRIBE_TAG', '0.0.0') 
version_number = os.environ.get('GIT_DESCRIBE_NUMBER', '0') 
version_number = '_' + version_number if version_number != '0' else ''

with open('recipe.yaml', 'w') as fout:
    fout.write("context:\n")
    fout.write("  name: pyrs\n")
    fout.write("  data: load_setup_py_data()\n")
    fout.write("  license: data.get('license')\n")
    fout.write("  description: data.get('description')\n")
    fout.write("  url: data.get('url')\n")
    fout.write("  version: {}\n".format(version_tag + version_number))
    fout.write("\n")
    fout.write("package:\n")
    fout.write("  name: pyrs\n")
    fout.write("  version: '{{ version }}'\n")
    fout.write("\n")
    fout.write("source:\n")
    fout.write("  path: ..\n")
    fout.write("\n")
    fout.write("build:\n")
    fout.write("  noarch: python\n")
    fout.write("  string: py{{py}}\n")
    fout.write("  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv'\n")
    fout.write("\n")
    fout.write("requirements:\n")
    fout.write("  host:\n")
    fout.write("    - python\n")
    fout.write("    - versioningit\n")
    fout.write("\n")
    fout.write("  build:\n")
    fout.write("    - configparser\n")
    fout.write("    - mantidworkbench\n")
    fout.write("    - qtpy\n")
    fout.write("    - pytest\n")
    fout.write("    - uncertainties\n")
    fout.write("    - vtk\n")
    fout.write("    - setuptools\n")
    fout.write("    - versioningit\n")
    fout.write("    - pandas\n")
    fout.write("\n")
    fout.write("  run:\n")
    fout.write("    - configparser\n")
    fout.write("    - mantidworkbench\n")
    fout.write("    - qtpy\n")
    fout.write("    - uncertainties\n")
    fout.write("    - vtk\n")
    fout.write("    - pandas\n")
    fout.write("\n")
    fout.write("test:\n")
    fout.write("  imports:\n")
    fout.write("    - pyrs\n")
    fout.write("\n")
    fout.write("about:\n")
    fout.write("  home: '{{ url }}'\n")
    fout.write("  license: '{{ license }}'\n")
    fout.write("  license_family: GPL3\n")
    fout.write("  license_file: ../LICENSE\n")
    fout.write("  summary: '{{ description }}'\n")
    fout.write("\n")
    fout.write("extra:\n")
    fout.write("  recipe-maintainers:\n")
    fout.write("    - JeanBilheux\n")
    fout.write("    - peterfpeterson\n")
    fout.write("    - fanchercm\n")