# this uses the action to merge special branches on push
# https://github.com/marketplace/actions/merge-branch
name: Merge protected branches

on:
  workflow_dispatch:
  push:
    branches: [qa, main]

jobs:
  merge-into-next:
    runs-on: ubuntu-latest
    # do not run in forks
    if: ${{ github.repository_owner == 'neutrons' }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: next  # going to commit to here
          fetch-depth: 0  # full git repository
      - name: fetch qa
        if: ${{ github.ref_name == 'qa' }}
        run: git fetch origin qa:qa
      - name: fetch main
        if: ${{ github.ref_name == 'main' }}
        run: git fetch origin main:main
      - name: set git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          run-install: false
      - name: merge qa into next
        if: ${{ github.ref_name == 'qa' }}
        run: |
          PREV_VERSION=$(pixi project version get)
          NEXT_VERSION=$(echo ${PREV_VERSION} | awk -F.dev -v OFS=.dev '{$NF += 1 ; print}')
          echo "Previous version on next ${PREV_VERSION}"
          echo "Next version will be ${NEXT_VERSION}"
          # check that there is something to merge
          git merge origin/qa -m "Merge qa into next" && exit 0 #  exit if everything is fine
          # commit and advance the version
          pixi project version set ${NEXT_VERSION}
          git commit -m "Set version to ${NEXT_VERSION}"
      - name: merge main into next
        if: ${{ github.ref_name == 'main' }}
        run: |
          # check that there is something to merge
          git merge origin/main -m "Merge main into next" && exit 0 #  exit if everything is fine
          echo "use pixi to update the minor version"
          # advance the version
          pixi project version minor # move to next minor
          NEXT_VERSION=$(pixi project version get | sed -E 's/\.dev.+//') # get version without dev
          NEXT_VERSION=$(echo ${NEXT_VERSION}.dev0)
          echo "Settind dev version to be ${NEXT_VERSION}"
          pixi project version set ${NEXT_VERSION}
          # commit the new version
          git commit -m "Set version to ${NEXT_VERSION}"
